version: 0.9.{build}

skip_tags: true # avoid deploy to GitHub loop 
# enable patching of AssemblyInfo.* files with appveyor version
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

image: Visual Studio 2019

configuration:
- Release

before_build:
- nuget restore -Verbosity quiet

build:
  verbosity: minimal              # MSBuild verbosity level

artifacts:
- path: bin\$(configuration)
  name: ShaderForm

deploy:
  release: $(appveyor_build_version)
  description: 'Released Created By Appveyor'
  provider: GitHub
  auth_token:
    secure: rgkHI4xJxcv3RdU4raAipHeo5lbwXL8uMblC8lPQm9esgm0c89S869xBwoHIZ/aS
  artifact: Latest build
  draft: false
  prerelease: false
  on:
    branch: master                # release from master branch only
#    appveyor_repo_tag: true       # deploy on tag push only
